export const StatusMessages = {
	UNKNOWN_ERROR: "unknown error",
	SUCCESS: "success",
	DOC_ALREADY_EXISTS: "doc already exists",
	DOC_NOT_EXIST: "doc not exist",
	DOC_EDIT_IN_PROGRESS: "doc edit in progress",
	LOGIN_REQUIRED: "login required",
	INVALID_ACCESS: "invalid access",
	MERGE_CONFLICT: "merge conflict",
	DOC_DELETED: "doc deleted",
	DOC_REDIRECT : "doc redirect",
	NO_FILE : "no file",
	NO_SELECTED_FILE : "no selected file",
	NOT_ALLOWED_FILE : "not allowed file",
};
